### ISSUE TITLE
CF Bridge integration test has a random test failures 

### ISSUE THREAD

**Issue by sasrin** [cloudfoundry-incubator/cf-abacus#104] opened 2015-10-20 04:35 UTC
```

  [31m  1) submit runtime usage to usage collector[0m


[92m [0m[32m 0 passing[0m[90m (26s)[0m
[31m  1 failing[0m

[0m  1) abacus-cf-bridge-itest submit runtime usage to usage collector:
[0m[31m     Uncaught AssertionError: expected undefined to equal 0.5[0m[90m
      at checkAllTimeWindows (lib/test/test.js:165:62)
      at Object.callback (lib/test/test.js:172:13)
      at Request._callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/lib/index.js:165:16)
      at Request.self.callback (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:198:22)
      at Request.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1082:10)
      at IncomingMessage.<anonymous> (/home/travis/build/cloudfoundry-incubator/cf-abacus/node_modules/abacus-request/node_modules/request/request.js:1009:12)
      at _stream_readable.js:908:16
[0m



Run time 27028ms

npm ERR! Linux 2.6.32-042stab108.8
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.7/bin/node" "/home/travis/.nvm/versions/node/v0.12.7/bin/npm" "run" "itest" "--" "-o" "4" "-i" "4" "-u" "4"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! abacus-cf-bridge-itest@0.0.2-rc.1 itest: `mocha --command "-o" "4" "-i" "4" "-u" "4"`

```

**Comment by georgethebeatle** [comment] 2015-10-20 11:07
It seems that the first window from aggregated usage is missing `consuming` data. The problem reproduces every 5th or 6th run and increasing the timeout of the test does not help.

The response:
```json
{
  "organization_id": "e8139b76-e829-4af3-b332-87316b1c0a6c",
  "resources": [
    {
      "resource_id": "linux-container",
      "plans": [
        {
          "plan_id": "basic",
          "aggregated_usage": [
            {
              "metric": "memory",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "cost": 0,
                    "summary": null,
                    "charge": null
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00007,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00007,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00007,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00007,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ]
              ]
            }
          ],
          "windows": [
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ]
          ]
        }
      ],
      "aggregated_usage": [
        {
          "metric": "memory",
          "windows": [
            [
              {
                "quantity": 0,
                "summary": null,
                "charge": null
              }
            ],
            [
              {
                "quantity": {
                  "consumed": 0,
                  "consuming": 0.5,
                  "since": 1445337857762
                },
                "summary": 0.0013494444444444443,
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "quantity": {
                  "consumed": 0,
                  "consuming": 0.5,
                  "since": 1445337857762
                },
                "summary": 0.0013494444444444443,
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "quantity": {
                  "consumed": 0,
                  "consuming": 0.5,
                  "since": 1445337857762
                },
                "summary": 0.0013494444444444443,
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "quantity": {
                  "consumed": 0,
                  "consuming": 0.5,
                  "since": 1445337857762
                },
                "summary": 0.0013494444444444443,
                "charge": 1.889222222222222e-7
              }
            ]
          ]
        }
      ],
      "windows": [
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ]
      ]
    }
  ],
  "spaces": [
    {
      "space_id": "a7e44fcd-25bf-4023-8a87-03fba4882995",
      "resources": [
        {
          "resource_id": "linux-container",
          "plans": [
            {
              "plan_id": "basic",
              "aggregated_usage": [
                {
                  "metric": "memory",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "cost": 0,
                        "summary": null,
                        "charge": null
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "cost": {
                          "burned": 0,
                          "burning": 0.00007,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "cost": {
                          "burned": 0,
                          "burning": 0.00007,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "cost": {
                          "burned": 0,
                          "burning": 0.00007,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "cost": {
                          "burned": 0,
                          "burning": 0.00007,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ]
                  ]
                }
              ],
              "windows": [
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ]
              ]
            }
          ],
          "aggregated_usage": [
            {
              "metric": "memory",
              "windows": [
                [
                  {
                    "quantity": 0,
                    "summary": null,
                    "charge": null
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 0.5,
                      "since": 1445337857762
                    },
                    "summary": 0.0013494444444444443,
                    "charge": 1.889222222222222e-7
                  }
                ]
              ]
            }
          ],
          "windows": [
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ]
          ]
        }
      ],
      "consumers": [
        {
          "consumer_id": "ALL",
          "resources": [
            {
              "resource_id": "linux-container",
              "plans": [
                {
                  "plan_id": "basic",
                  "aggregated_usage": [
                    {
                      "metric": "memory",
                      "windows": [
                        [
                          {
                            "quantity": 0,
                            "cost": 0,
                            "summary": null,
                            "charge": null
                          }
                        ],
                        [
                          {
                            "quantity": {
                              "consumed": 0,
                              "consuming": 0.5,
                              "since": 1445337857762
                            },
                            "cost": {
                              "burned": 0,
                              "burning": 0.00007,
                              "since": 1445337857762
                            },
                            "summary": 0.0013494444444444443,
                            "charge": 1.889222222222222e-7
                          }
                        ],
                        [
                          {
                            "quantity": {
                              "consumed": 0,
                              "consuming": 0.5,
                              "since": 1445337857762
                            },
                            "cost": {
                              "burned": 0,
                              "burning": 0.00007,
                              "since": 1445337857762
                            },
                            "summary": 0.0013494444444444443,
                            "charge": 1.889222222222222e-7
                          }
                        ],
                        [
                          {
                            "quantity": {
                              "consumed": 0,
                              "consuming": 0.5,
                              "since": 1445337857762
                            },
                            "cost": {
                              "burned": 0,
                              "burning": 0.00007,
                              "since": 1445337857762
                            },
                            "summary": 0.0013494444444444443,
                            "charge": 1.889222222222222e-7
                          }
                        ],
                        [
                          {
                            "quantity": {
                              "consumed": 0,
                              "consuming": 0.5,
                              "since": 1445337857762
                            },
                            "cost": {
                              "burned": 0,
                              "burning": 0.00007,
                              "since": 1445337857762
                            },
                            "summary": 0.0013494444444444443,
                            "charge": 1.889222222222222e-7
                          }
                        ]
                      ]
                    }
                  ],
                  "windows": [
                    [
                      {
                        "charge": 0
                      }
                    ],
                    [
                      {
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "charge": 1.889222222222222e-7
                      }
                    ]
                  ]
                }
              ],
              "aggregated_usage": [
                {
                  "metric": "memory",
                  "windows": [
                    [
                      {
                        "quantity": 0,
                        "summary": null,
                        "charge": null
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ],
                    [
                      {
                        "quantity": {
                          "consumed": 0,
                          "consuming": 0.5,
                          "since": 1445337857762
                        },
                        "summary": 0.0013494444444444443,
                        "charge": 1.889222222222222e-7
                      }
                    ]
                  ]
                }
              ],
              "windows": [
                [
                  {
                    "charge": 0
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ],
                [
                  {
                    "charge": 1.889222222222222e-7
                  }
                ]
              ]
            }
          ],
          "windows": [
            [
              {
                "charge": 0
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ],
            [
              {
                "charge": 1.889222222222222e-7
              }
            ]
          ]
        }
      ],
      "windows": [
        [
          {
            "charge": 0
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ],
        [
          {
            "charge": 1.889222222222222e-7
          }
        ]
      ]
    }
  ],
  "start": 1445337857762,
  "end": 1445337857762,
  "region": "eu-gb",
  "id": "k/e8139b76-e829-4af3-b332-87316b1c0a6c/t/0001445337858921-0-1-0",
  "processed": 1445337858921,
  "windows": [
    [
      {
        "charge": 0
      }
    ],
    [
      {
        "charge": 1.889222222222222e-7
      }
    ],
    [
      {
        "charge": 1.889222222222222e-7
      }
    ],
    [
      {
        "charge": 1.889222222222222e-7
      }
    ],
    [
      {
        "charge": 1.889222222222222e-7
      }
    ]
  ]
}
```

**Comment by hsiliev** [comment] 2015-10-20 11:32
Refactored the test with https://github.com/cloudfoundry-incubator/cf-abacus/pull/105:
* using correct start/stop process order
* polling the usage response to remove hardcoded timeouts and speed up the test

Seems that this change somehow masks the problem with the missing `consuming` data. We cannot reproduce the problem locally anymore. This makes me think it is a race condition of a kind.

**Comment by jsdelfino** [comment] 2015-10-22 19:54
Ben, could you take a look at this one and comment back here? Thanks!

**Comment by jsdelfino** [comment] 2015-10-22 19:59
This build: https://travis-ci.org/cloudfoundry-incubator/cf-abacus/jobs/86877463 shows the error

**Comment by jsdelfino** [comment] 2015-10-24 03:02
While Ben's fix (partially) addresses the reported issue, I think we'll need to define a clean strategy to check time-dependent usage result values across the board in all integration and end to end tests and use that strategy here as well.

**Comment by jsdelfino** [comment] 2015-11-04 07:14
Closing as we're not seeing these issues anymore. Please reopen if needed.

**Closed by jsdelfino** 2015-11-04 07:14 UTC
Labels: bug
