### ISSUE TITLE
Incorrect keys and times in generated error docs

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#328] opened 2016-06-03 16:28 UTC
The keys of the error docs generated to record business errors while processing collected usage should include the input usage key and time. To allow this, the error key generation functions should be passed the input key and input time, like the output key generation functions.

Also, it looks like the error docs generated by the usage collector service are missing the usage space id.

**Comment by jsdelfino** [comment] 2016-06-03 16:33
For example here:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/46fcfc48beac16e477d355c57d64b11db39c0bd9/lib/metering/collector/src/index.js#L92

The ```etime(udoc)``` function should have an additional parameter like this ```time(udoc, time)```.
Same idea for the ```ekey``` function.

**Comment by KRuelY** [comment] 2016-06-06 02:37
Hi,

I believe #330 will address the issues mentioned here. It also includes a bug fix on the output get api due to 6402cc426fd0d6a1d3929f620d41d07650adb4b2.

The one thing to mention here is that adding the collector's itime(seqid) at the collector's etime will allow duplicate of error docs.

**Closed** 2016-06-13 15:47 UTC
Labels: bug, unscheduled
