### ISSUE TITLE
ERR Error: invalid schema, expected mongodb

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#650] opened 2017-06-01 13:49 UTC
Getting this error while using mongodb on CF.

ERR Error: invalid schema, expected mongodb

**Comment by hsiliev** [comment] 2017-06-01 14:07
Usually this is caused by wrong URL in one of the env.variables for DB configuration, described here: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/conf.md#database

Please check if your
* `DB` is a valid mongo URL, such as `mongodb://user:password@10.11.21.248:27017,10.11.21.249:27017,10.11.21.250:27017/dbname?replicaSet=replicaSetName`
* `DBCLIENT` is set to `abacus-mongoclient`

**Comment by cfmagnum** [comment] 2017-06-01 14:15
I have followed the steps here. Removed the DB variable as given here. And created the service instance of mongodb and binded it to every application of abacus.

https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/conf.md#cloud-foundry-configuration

**Comment by hsiliev** [comment] 2017-06-01 14:45
Can you please run `cf env` on one of the abacus applications and post the sanitized `VCAP_SERVICES` section?

**Comment by cfmagnum** [comment] 2017-06-01 15:00
Yes I checked it. It's having the mongo credentials in VCAP_SERVICES.

**Comment by hsiliev** [comment] 2017-06-01 15:52
The service instance bound to the apps should be called 'db' as the env. variable in the manifest.yml

**Comment by cfmagnum** [comment] 2017-06-06 11:31
My instance name was not 'db' before. Changed it to db now. It's working fine now. Thanks.

But service instance name should be customizable rignt?

**Comment by hsiliev** [comment] 2017-06-06 12:17
In general it should be customizable. We use a naming convention for the service instance name to enable adding more db storage (mongo dbclient only) in production.

Potentially there will be a problem if you need to bind another service with name `db` to Abacus apps. Since we do not require or support more DBs I regard this as improbable scenario and will close the issue.

In case you need to have more services bound to Abacus apps with the name `db` please reopen it.

**Closed by hsiliev** 2017-06-06 12:17 UTC
Labels: unscheduled

**Comment by ghost** [comment] 2019-10-21 14:13
Error!Error: Invalid schema, expected `mongodb` or `mongodb+srv`

**Comment by hsiliev** [comment] 2019-10-21 19:37
@mrsinghda Can you share if this happens locally on your computer or on CF? What version of abacus are you using?
