### ISSUE TITLE
Query view with stale set to ok will get nothing - abacus-pouchserver 

### ISSUE THREAD

**Issue by nicolelovecoding** [cloudfoundry-incubator/cf-abacus#689] opened 2017-07-19 16:11 UTC
First start the abacus-pouchserver listening on port 5984

```
const start = (module) => {
      cp.spawn('npm', ['run', 'start'], {
        cwd: moduleDir(module),
        env: clone(process.env)
      });
    };
start('abacus-pouchserver');
```
Then create db and insert docs and view
In the end query view
```
var db = new PouchDB('http://admin:admin@localhost:5984/cf-names-0-201602');
db.query('design_name/view_name', {
      stale: 'ok',
      limit: limit,
      skip: skip,
      include_docs: true,
      reduce: false
    });
```
But if I set stale as true or false, I could get what I want.

**Comment by hsiliev** [comment] 2017-07-19 19:14
@nicolelovecoding Can you also post the definition of the function or a description what it should do? 

The [PouchDB doc](https://pouchdb.com/api.html#query_index) says `Returns results immediately, even if they’re out-of-date.`. I wonder can it be that the view is not built yet? What happens if you call the `query` second time after a timeout of let's say 5 seconds?

**Comment by nicolelovecoding** [comment] 2017-07-19 20:23
@hsiliev yes, it will returns an empty array immediately. 
So what I did is that first start the abacus-pouchserver locally and then create db, insert docs into the db including view. In the end, query the view. It returns immediately, but I got an empty array which are not supposed to be. 
If I change the variable stale to true/false, it returns returns immediately with the data I am expecting.

**Comment by hsiliev** [comment] 2017-07-19 20:28
And what about second call after some timeout?

BTW abacus provides the pouchserver as a convenience utility app that delegates most of the logic to PouchDB modules underneath. I have a feeling that the your questions will be answered by the experts at https://github.com/pouchdb/pouchdb, unless the problem is with out wrapper application or how we handle the PouchDB modules.

**Comment by nicolelovecoding** [comment] 2017-07-19 20:32
@ The second call after timeout, returns the same empty array.

**Comment by hsiliev** [comment] 2017-07-19 20:41
We can try to narrow the problem by trying to reproduce with
* CouchDB installed locally on your machine for example
* PouchDB server: https://github.com/pouchdb/pouchdb-server

This can at least show us that the problem is (or is not) with abacus-pouchserver

**Comment by nicolelovecoding** [comment] 2017-07-27 21:09
@hsiliev I have install a CouchDB locally, the same issue. With stale: 'ok', I will get an empty array. If I remove it, then I will get what I want.

**Comment by hsiliev** [comment] 2017-07-27 21:28
Both PouchDB and our wrapper `abacus-pouchserver` are trying to mimic the original CouchDB. Since CouchDB behaves the same way we can consider this "as designed". Still no idea why your query returns no results. 

I would suggest to file an issue with CouchDB to get to the root cause.

Closing the issue, but feel free to reopen it in case you feel we can change Abacus to fit to your use case (like bumping pouchdb version or changing a configuration).

**Closed by hsiliev** 2017-07-27 21:28 UTC
Labels: unscheduled
