### ISSUE TITLE
Submitting resource usage for runtimes

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#40] opened 2015-09-22 22:32 UTC
Looking at the usage submission docs (https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/api.md) it seems that when submitting the usage for runtimes, the resource_instance_id would be the right  field to submit the buildpack_guid to specify which actual runtime is being used by the consumer (application). Is that the correct interpretation of the api ?

Another concern is what happens when resource_instance_id is missing in initial submissions. In some cases it may not be available initially but only provided later - for example CF may not provide it in start event but in stop. In that case, can the collector propagate runtime id to other submissions for the same consumer_id  ?

**Comment by jsdelfino** [comment] 2015-09-23 01:47
> it seems that when submitting the usage for runtimes, the resource_instance_id would be the right field to submit the buildpack_guid

For services, you can use:
```
resource_id: <service id>
resource_instance_id: <service instance id>
consumer_id: <app id> // if known
```

For app usage, use:
```
resource_id: <buildpack id>
resource_instance_id: <app id>
consumer_id: <app id>
```

> ... What happens when resource_instance_id is missing in initial submissions... can the collector propagate runtime id to other submissions for the same consumer_id

I'm not following that part. With 'resource_instance_id is missing' are you saying that the ```buildpack id``` is missing (I'm inferring that from the fact that you were asking about putting the buildpack id in the resource_instance_id field in your previous question)? Did you mean ```buildpack id``` as well when you said ```runtime id``` later? Not sure either what you meant by 'propagate runtime id to other submissions for the same consumer_id'. Can you help me understand that part with an example maybe?

**Comment by jsdelfino** [comment] 2015-09-23 01:57
Also look at the Abacus CF app usage bridge
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/src/index.js#L237
for an example of what to do.

I believe the bridge does the right thing with these ids. It doesn't seem to set the consumer id but I don't think that's absolutely necessary. Setting the consumer id is only needed if you want to see an aggregate of app usage per consumer (i.e. per app) in the summary report.

**Comment by piotrprzybylski** [comment] 2015-09-23 15:15
In the docs, tests and the bridge the resource_id determines how the usage submission is handled by matching definition in lib/config/resource/lib/resources.
This led me to assume that resource_id determines a set of resources - application runtimes, 
which are metered in the same way. 

If resource_id is a buildpack guid, it may cause proliferation of resource definitions for similar resources, for example different versions of nodejs runtime. These versions may be added at any time so a mechanism to register them may be needed.

There is also a problem with custom buildpacks which can be provided during application deployment (https://docs.cloudfoundry.org/buildpacks/custom.html). In that case, the buildpack guid is unknown and the application usage could not be measured.

The specific scenario of missing buildpack guid is following the bridge implementation. The submission is based on the first STARTED app usage event. In some cases - average is about 10% on Bluemix, 
the buildpack_guid and buildpack_name fields of the first STARTED event are null. If the buildpack_guid is needed to correctly submit, it must be obtained by some other means.

**Comment by hsiliev** [comment] 2015-09-23 15:36
@piotrprzybylski We actually report BUILDPACK_SET after the STARTED event (https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/src/index.js#L269). 

Any idea if BUILDPACK_SET events are reliable? If so this will help to add the needed buildpack field since the set event is fired almost immediately after start events.

**Comment by jsdelfino** [comment] 2015-09-23 15:44
> In the docs, tests and the bridge the resource_id determines how the usage submission is handled by matching definition in lib/config/resource/lib/resources. This led me to assume that resource_id determines a set of resources - application runtimes, which are metered in the same way. If resource_id is a buildpack guid, it may cause proliferation of resource definitions for similar resources, for example different versions of nodejs runtime. These versions may be added at any time so a mechanism to register them may be needed.

@piotrprzybylski: AIUI this is already covered in issue #38. Please review #38 and comment there if needed.

> There is also a problem with custom buildpacks which can be provided during application deployment (https://docs.cloudfoundry.org/buildpacks/custom.html). In that case, the buildpack guid is unknown and the application usage could not be measured.

As I mentioned in issue #37, Abacus does not make any assumption on the contents of the resource_id. You just need to provide a value for that resource_id to get usage aggregated for it (any value that makes sense to you, including 'unknown' for example if that allows you to categorize unknown buildpacks).

>  The specific scenario of missing buildpack guid is following the bridge implementation. The submission is based on the first STARTED app usage event. In some cases - average is about 10% on Bluemix, the buildpack_guid and buildpack_name fields of the first STARTED event are null. If the buildpack_guid is needed to correctly submit, it must be obtained by some other means.

Not sure if missing the buildpack info from the app usage STARTED event is a bug in the CF app usage event API or the expected behavior of that API. You may want to review the app usage BUILDPACK SET event as suggested by @hsiliev or raise an issue with the CF app usage event API to resolve this. If you're not getting the buildpack info from any app usage event, then you're correct that you'll need to obtain the buildpack info by some other means, as again Abacus will require a resource_id to aggregate usage for it.

**Comment by piotrprzybylski** [comment] 2015-09-23 17:16
@jsdelfino - Thank you, #37 and #38 suggested solution to the problem I tried to solve so I will continue discussion there.

**Comment by piotrprzybylski** [comment] 2015-09-23 18:44
@hsiliev - Yes, you submit the usage for BUILDPACK_SET event but the preceding start would still have to be submitted as unknown - what discussed in #37 and #38 would help with that submission and the unknown period would depend on the interval between events. I don't have detailed numbers but that interval is usually minutes. But we have also seen situation when there is START, followed by STOP, both without guid and without buildpack_set event between them. 
Also, from the 200k event sample sample there were about 42k of BUILDPACK_SET events and all of them contain the buildpack_guid (CF 210).

**Comment by piotrprzybylski** [comment] 2015-09-24 14:53
The lack of buildpack info in the initial START event is not a defect as explained at [1] - the information is not yet available and will be provided in the following BUILDPACK event.
[1] - https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/NCPE42LVC7YZUQZ7GQGBFHTWVJOLVOUB/

**Comment by jsdelfino** [comment] 2015-09-27 21:45
@piotrprzybylski, @hsiliev Is there any further discussion needed here or is a code change required? otherwise I'm planning to close this issue in a day or two.

**Comment by jsdelfino** [comment] 2015-09-30 03:16
Closing as there's no more discussion. Please reopen if needed.

**Closed** 2015-09-30 03:16 UTC
Labels: question
