### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#139] opened 2015-10-30 20:06 UTC
I had 50 orgs and each org has 5 spaces and each space has  5 apps and 5 services are bound to each app.

I was submitting usage for every instance at regular intervals of time (1 minute)

I noticed the following when i ran in local environment.
1. I received http status code 409.
2. There were timeouts
3. The aggregator failed to calculate the rated usage.

```javascript
{
  "orgs": 50,
  "spaces": 5,
  "apps": 5,
  "instances": 5,
  "interval": 60000,
  "requestsSent": 62500,
  "statusCodes": {
    "201": 38403,
    "400": 100,
    "HTTP response status code 500": 2122
  }
}
```

I am preparing a sheet with different counts of orgs. I will share them soon.

**Comment by jsdelfino** [comment] 2015-10-30 20:13
Hi @rajkiranrbala Looks like you're running into several problems here, which could be related or not, or share the same cause or not... Could you please create specific issues for each specific problem you are seeing, including a description of the steps to reproduce the problem, the API you're using, the payload you're sending, and a copy of the response or logs (showing that 409 status for example)? Thanks

**Comment by rajkiranrbala** [comment] 2015-10-30 20:37
Here is the code that submits the usage 

```javascript
'use strict';
const helper = require('./helper.js');

const debug = require('abacus-debug')('abacus-usage-submitter');
const edebug = require('abacus-debug')('e-abacus-usage-submitter');
const ndebug = require('abacus-debug')('n-abacus-usage-submitter');
const request = require('abacus-request');
const oauth = require('abacus-cfoauth');
const webapp = require('abacus-webapp');
const router = require('abacus-router');
const urienv  = require('abacus-urienv');
const cluster  = require('abacus-cluster');

cluster.singleton();
// Resolve service URIs
const uris = urienv({
  collector: 9080,
  auth_server: 9882
});

let systemToken;

const collectorHost = process.env.COLLECTOR || 'localhost:9080';

const secured = () => process.env.SECURED === 'true' ? true : false;

const ORGS = process.env.ORGS ? parseInt(process.env.ORGS) : 50;
const SPACES = process.env.SPACES ? parseInt(process.env.SPACES) :  5;
const APPS = process.env.APPS ?  parseInt(process.env.APPS) : 5;
const INSTANCES = process.env.INSTANCES ?  parseInt(process.env.INSTANCES) : 5;
const INTERVAL = process.env.INTERVAL ? parseInt(process.env.INTERVAL) : 1000 * 60 * 1;

let schedulers = [];
let instancesData = {};
const getInstanceKey = (o, s, a, n) => {
  return o + '-' + s + '-' + a + '-' + n;
};

const appendResult = (error, response, instanceData) => {
  if(response) {
    if(!instanceData.statusCodes[response.statusCode])
      instanceData.statusCodes[response.statusCode] = 0;
    instanceData.statusCodes[response.statusCode] += 1;
  }
  else if(error) {
    if(!instanceData.statusCodes[error.message])
      instanceData.statusCodes[error.message] = 0;
    instanceData.statusCodes[error.message] += 1;
  }
  else {
    if(!instanceData.statusCodes['UNKNOWN'])
      instanceData.statusCodes['UNKNOWN'] = 0;
    instanceData.statusCodes['UNKNOWN'] += 1;
  }
};

const postForInstance = (o, s, a, n) => {
  setTimeout(function() {
    const token = systemToken ? systemToken() : undefined;
    ndebug('Submitting usage for org %d space %d app %d instance %d', o, s, a, n);
    const now = new Date().getTime();
    const instanceData = instancesData[getInstanceKey(o,s,a,n)];
    request.post('http://:host/v1/metering/collected/usage', {
      host : collectorHost,
      headers : {
        'Content-Type' : 'application/json',
        'Authorization' : token
      },
      body: helper.getUsage(o, s, a, n, instanceData.lastRequestedTime + 1, now)
    }, (err, response) => {
      if(err) {
        edebug('Error submitting usage for org %d space %d app %d instance %d. %o',
          o, s, a, n, err);
      }
      const iData = instancesData[getInstanceKey(o,s,a,n)];
      appendResult(err, response, iData);
    });
    instanceData.lastRequestedTime = now;
    instanceData.requestsSent += 1;
  }, Math.random(1, 1000 * 10));
};

const schedulerForInstance = (o, s, a, n) => {
  setTimeout(function() {
    debug('Scheduling for org %d space %d app %d instance %d', o, s, a, n);
    instancesData[getInstanceKey(o,s,a,n)] = {
      'lastRequestedTime' : new Date().getTime(),
      'requestsSent' : 0,
      'statusCodes' : { }
    };
    schedulers.push(setInterval(function() {
      postForInstance(o, s, a, n);
    }, INTERVAL));
    debug('Scheduled for org %d space %d app %d instance %d', o, s, a, n);
  }, Math.random(1, 1000));
};

let startTime;
const schedule = () => {
  if(schedulers.length === 0) {
    for(let o=1; o<=ORGS; o++)
      for(let s=1; s<=SPACES; s++)
        for(let a=1; a<=APPS; a++)
          for(let n=1; n<=INSTANCES; n++)
            schedulerForInstance(o, s, a, n);
    startTime = new Date().getTime();
  }
  else {
    const error = new Error('Jobs were already scheduled');
    error.statusCode = 400;
    throw error;
  }
};

const cancel = () => {
  if(schedulers.length != 0) {
    schedulers.forEach(function(f){
      clearInterval(f);
    });
    schedulers = [];
    instancesData = {};
  }
  else {
    const error = new Error('No jobs were scheduled to cancel');
    error.statusCode = 400;
    throw error;
  }
};


const routes = router();

routes.get('/start', function (req, res, next) {
  schedule();
  return {
    body :  { 'ok' : true }
  };
});

routes.get('/stop', function (req, res, next) {
  cancel();
  return {
    body :  { 'ok' : true }
  };
});

routes.get('/stats/:id', function * (req, res, next) {
  return {
    body : instancesData[req.params.id]
  }
});

routes.get('/stats', function * (req, res, next) {
  return {
    body : instancesData
  };
});

routes.get('/summary', function * (req, res, next) {
  const summary = {
    orgs: ORGS,
    spaces: SPACES,
    apps: APPS,
    instances: INSTANCES,
    interval: INTERVAL,
    requestsSent: 0,
    statusCodes : {},
    startTime: new Date(startTime),
    endTime: new Date()
  };
  Object.keys(instancesData).forEach(function(instance) {
    summary.requestsSent += instancesData[instance].requestsSent;
    Object.keys(instancesData[instance].statusCodes).forEach(function(status) {
      if(!summary.statusCodes[status])
        summary.statusCodes[status] = 0;
      summary.statusCodes[status] += instancesData[instance].statusCodes[status];
    });
  });
  return {
    body: summary
  }
});



// Create a submitter service app
const submitter = () => {
  const app = webapp();
  app.use(routes);
  return app;
};


// Command line interface, create the submitter app and listen
const runCLI = () => {
  // Cache and schedule the system token renewal
  if (secured()) {
    systemToken = oauth.cache(uris.auth_server, process.env.CLIENT_ID,
      process.env.CLIENT_SECRET, 'abacus.usage.write abacus.usage.read');

    systemToken.start();
  }

  submitter().listen();
  if(cluster.isWorker())
    schedule();
};

// Export our public functions
module.exports = submitter;
module.exports.runCLI = runCLI;

```

**Comment by jsdelfino** [comment] 2015-10-31 07:51
@rajkiranrbala and @piotrprzybylski: @sasrin tried your test, and I did a bit of testing myself as well, and it looks like you need to do 3 things to get over the problems you've seen:

1. Try to change your client program to avoid consuming all the socket handles available on your system, as that (a) prevents the Abacus services from opening connections (b) causes the client program to fail with connection issues as well. In Abacus, we typically throttle our HTTP connection requests to avoid causing that kind of resource exhaustion and crash. You could use a similar technique using the Abacus-throttle module.

2. Make sure your account stub is able to return the pricing configuration for your test resources. From our earlier chat, it seems that your test environment didn't have that pricing config, causing repeated errors in the Rating service (and an avalanche of calls failing to retrieve that config without having the opportunity to cache it).

3. See if you can increase the default timeout in the Abacus-breaker module, as (perhaps as side effects of issues 1 and 2) you may be running into timeouts causing the circuit breakers to open a bit too often. Try to increase the default timeout (try 60000 for example) on line 35 of lib/utils/abacus-breaker/src/index.js. That timeout can also be set programmatically, but changing that one line will change it across the board, just to try things out.

**Comment by jsdelfino** [comment] 2015-10-31 08:31
Commit 06be4d3 adds some caching to the provisioning service to avoid bombarding the provisioning db with unnecessary requests to retrieve the same resource configs over and over. This should help with the reported issue as well as all these database calls contributed to hurting the performance of the db and causing timeouts while accessing it.

**Comment by jsdelfino** [comment] 2015-10-31 08:38
With the fix to the provisioning stub, I consistently see successful runs of:
```
npm run perf -- -o 50 -i 5 -u 25
```
This takes less than 2 mins on my laptop, no timeouts, no circuit breaker failures.

**Comment by jsdelfino** [comment] 2015-11-04 07:12
With caching in the provisioning service and batching of the calls to get the pricing country and price config in the rating service, this is now fixed.

**Closed by jsdelfino** 2015-11-04 07:12 UTC
Labels: bug
